<?php

// autoload_namespaces.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'PasswordPolicy' => array($baseDir . '/lib'),
    'PasswordLib' => array($baseDir . '/lib'),
);
